---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-merge-conflict
    name: Unresolved merge conflicts
  - id: end-of-file-fixer
    name: (Non-binary) files end with a new-line
  - id: check-case-conflict
    name: Conflict in case-insensitive filesystems
  - id: check-symlinks
    name: Broken symlinks
  - id: trailing-whitespace
    name: Trim trailing whitespace
    files: |
      (?x)^(
        (.*)\.(c3typ|py|js|json|jsx|tsx|ts|less|css|scss|csv)
      )
    exclude: |
      (?x)(
        .*\/Translation\/.*\.csv
      )
  - id: check-added-large-files
    name: Check for large files
- repo: https://gitlab.com/bmares/check-json5
  rev: v1.0.0
  hooks:
  - id: check-json5
    name: Lint JSON files
    files: .*/(c3|ui|metadata|source)/.*\.json
- repo: https://github.com/psf/black
  rev: 23.7.0
  hooks:
  - id: black
    name: Python formatter
    types:
      - python
    files: |
      (?x)^(
        (.*)\.py
      )
    args: ["-l 120"]
- repo: local
  hooks:
  - id: c3typ-lint
    name: C3 type linter
    entry: ./scripts/hooks/c3typ-lint.sh
    language: script
    files: |
      (?x)(
        .*\.c3typ
      )
  - id: copyright
    name: Copyright header
    entry: ./scripts/hooks/copyright-header.sh
    language: script
    files: |
      (?x)(
        (.*)\.java$|
        (.*)\.(c3typ|js|jsx|py|ts|tsx|css|scss)$
      )
  - id: npm-lint
    name: npm linter
    entry: ./scripts/hooks/npm-lint.sh
    pass_filenames: false
    language: script
    files: |
      (?x)^(
        (.*)\.(c3typ|js|json|jsx|tsx|ts|less|css|scss|csv)$
      )
  - id: c3-pylint
    name: C3 Python Linter
    entry: ./scripts/hooks/py-lint.sh
    language: script
    verbose: true
    types:
      - python
  - id: translation
    name: Translation linter
    entry: ./scripts/hooks/translation-lint.sh
    language: script
    files: |
      (?x)^(
        (.*)\/Translation\/.*\.csv
      )
