---
- hosts: localhost
  gather_facts: true
  vars_files:
    - vars/main.yml
  
  tasks:
    - block:
      - name: Include pre-commit role
        include_role:
          name: pre-commit
      become: false
